name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodule
      run: git submodule update --init --recursive
    - name: docker
      run: docker build -t aidrive .
    - name: make
      run: |
        source setup.sh
        mkdir build && cd build
        cib cmake .. -DCMAKE_BUILD_TYPE=Release
        cib make -j20
    - name: test
      run: |
        source setup.sh
        cd build
        cib ctest
